import type { Metadata } from "next";
import { headers } from "next/headers";
import { TYPESHala_SITE_URL } from "@/lib/site-urls";

import { fetchLatestRelease } from "./_lib/release";
import {
  TYPESHALA_AUTHOR,
  TYPESHALA_AUTHOR_URL,
  TYPESHALA_DATE_PUBLISHED,
  TYPESHALA_DESCRIPTION,
  TYPESHALA_DEVANAGARI,
  TYPESHALA_FAQ,
  TYPESHALA_FEATURE_LIST,
  TYPESHALA_KEYWORDS,
  TYPESHALA_LICENSE,
  TYPESHALA_NAME,
  TYPESHALA_PLATFORMS,
  TYPESHALA_REPO_URL,
  TYPESHALA_GITHUB_URL,
  TYPESHALA_SCREENSHOTS,
} from "@/lib/typeshala-content";

/**
 * This route is the standalone Typeshala product site: proxy.ts serves it at the
 * root of the typeshala subdomain and redirects every other page route to the
 * portfolio domain, so nothing here links back with a relative URL.
 *
 * `title.absolute` is deliberate. The root layout's template appends
 * " | Abhishek Gaire Portfolio" to every non-absolute title, which was the
 * first half of the bug this metadata used to have — the page branded itself as
 * a download page for a portfolio site, and inherited that site's
 * `application-name` too.
 */
export const metadata: Metadata = {
  metadataBase: new URL(TYPESHala_SITE_URL),
  title: {
    absolute: `${TYPESHALA_NAME}: Free Nepali & English Typing Tutor (Preeti, Romanized)`,
  },
  description: TYPESHALA_DESCRIPTION,
  applicationName: TYPESHALA_NAME,
  authors: [{ name: TYPESHALA_AUTHOR, url: TYPESHALA_AUTHOR_URL }],
  creator: TYPESHALA_AUTHOR,
  publisher: TYPESHALA_AUTHOR,
  keywords: TYPESHALA_KEYWORDS,
  category: "education",
  alternates: {
    canonical: "/",
  },
  openGraph: {
    type: "website",
    url: "/",
    siteName: TYPESHALA_NAME,
    locale: "en_US",
    // /typeshala/opengraph-image is generated by app/typeshala/opengraph-image.tsx.
    images: [
      {
        url: "/typeshala/opengraph-image",
        width: 1200,
        height: 630,
        alt: `${TYPESHALA_NAME} (${TYPESHALA_DEVANAGARI}) — free, open-source Nepali and English typing tutor for Windows, macOS and Linux`,
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    images: ["/typeshala/opengraph-image"],
  },
  robots: {
    index: true,
    follow: true,
  },
  /*
    Declaring `icons` here replaces the root layout's whole `icons` object
    rather than merging with it, so `apple` has to be restated — omitting it
    silently dropped the apple-touch-icon from this page.
  */
  icons: {
    icon: [{ url: "/typeshala/icon.svg", type: "image/svg+xml" }],
    apple: [{ url: "/typeshala/apple-touch-icon.png" }],
  },
};

/**
 * The version and download URL are read from the release API rather than
 * hardcoded, so the structured data goes stale the day a new tag ships instead
 * of quietly lying until someone remembers to edit it.
 *
 * Returns null when GitHub cannot be reached, and the caller then omits the
 * fields entirely — an absent `softwareVersion` is a weaker signal, a wrong one
 * is a rich-result penalty.
 */
async function getReleaseMeta() {
  const { data, failed } = await fetchLatestRelease();
  if (failed || !data) return null;

  // published_at arrives as full ISO ("2026-10-01T…Z"); schema.org wants the
  // calendar date. toISOString is UTC-based, and GitHub timestamps are UTC, so
  // slicing is exact rather than timezone-adjacent.
  const publishedAt = data.published_at
    ? new Date(data.published_at).toISOString().slice(0, 10)
    : null;

  return {
    version: data.tag_name.replace(/^v/, ""),
    downloadUrl: data.html_url,
    publishedAt,
  };
}

export default async function TypeshalaLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // proxy.ts stamps x-nonce on the subdomain rewrite response and re-sets the
  // CSP on it, so this script tag can execute. Do not drop the attribute.
  const nonce = (await headers()).get("x-nonce") ?? "";
  const release = await getReleaseMeta();

  const softwareJsonLd = {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    name: TYPESHALA_NAME,
    alternateName: TYPESHALA_DEVANAGARI,
    url: TYPESHala_SITE_URL,
    applicationCategory: "EducationalApplication",
    applicationSubCategory: "Typing tutor",
    operatingSystem: TYPESHALA_PLATFORMS,
    description: TYPESHALA_DESCRIPTION,
    inLanguage: ["en", "ne"],
    ...(release
      ? {
          softwareVersion: release.version,
          downloadUrl: release.downloadUrl,
          // First public release, fixed; latest release date, live. Swapping
          // them — a moving datePublished or a stale dateModified — is the
          // mistake this split exists to prevent. A null dateModified would
          // serialise as `"dateModified": null`, which reads as a claim that
          // the app was never modified, so it is omitted instead of nulled.
          ...(release.publishedAt
            ? { dateModified: release.publishedAt }
            : null),
        }
      : null),
    datePublished: TYPESHALA_DATE_PUBLISHED,
    /*
     * Resolved against the site URL because schema.org wants an absolute URL
     * and `src` is a root-relative file path. Resolving is idempotent — if
     * the screenshot ever moves back to a hosted absolute URL, new URL()
     * returns it unchanged and nothing here needs editing.
     */
    screenshot:
      TYPESHALA_SCREENSHOTS.length > 0
        ? new URL(TYPESHALA_SCREENSHOTS[0].src, TYPESHala_SITE_URL).toString()
        : undefined,
    featureList: TYPESHALA_FEATURE_LIST,
    license: TYPESHALA_LICENSE,
    // Free and open source, stated rather than implied. `offers` is what makes
    // the price legible to a shopping-style result, and `isAccessibleForFree`
    // is the flag Google reads for "no cost".
    offers: {
      "@type": "Offer",
      price: "0",
      priceCurrency: "USD",
    },
    isAccessibleForFree: true,
    author: {
      "@type": "Person",
      name: TYPESHALA_AUTHOR,
      url: TYPESHALA_AUTHOR_URL,
    },
    codeRepository: TYPESHALA_REPO_URL,
    // The GitHub mirror, kept as an explicit link rather than left implicit:
    // it is where the installers actually live.
    sameAs: [TYPESHALA_REPO_URL, TYPESHALA_GITHUB_URL],
  };

  const faqJsonLd = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: TYPESHALA_FAQ.map(({ question, answer }) => ({
      "@type": "Question",
      name: question,
      acceptedAnswer: { "@type": "Answer", text: answer },
    })),
  };

  return (
    <>
      {/*
        Two documents, not one. `SoftwareApplication` is what makes the page
        eligible for a rich result; `FAQPage` needs its own top-level type, so
        merging them into an @graph here would be the only way to keep both and
        it buys nothing — both are emitted as sibling top-level scripts.

        One @graph on this site already (app/projects/[slug]/page.tsx) and that
        one genuinely needs it: BreadcrumbList has no role of its own on the
        page. These two are each independently addressable, so they stay
        separate.
      */}
      <script
        type="application/ld+json"
        nonce={nonce}
        suppressHydrationWarning
        dangerouslySetInnerHTML={{ __html: JSON.stringify(softwareJsonLd) }}
      />
      <script
        type="application/ld+json"
        nonce={nonce}
        suppressHydrationWarning
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />
      {children}
    </>
  );
}